version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./ai-solution-reviewer-backend
    env_file:
      - ./ai-solution-reviewer-backend/.env.example
    volumes:
      - ./ai-solution-reviewer-backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./ai-solution-reviewer-frontend
    volumes:
      - ./ai-solution-reviewer-frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: